#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${NOTIFICATION_POSTGRES_USER} WITH PASSWORD '${NOTIFICATION_POSTGRES_PASSWORD}';
    CREATE DATABASE ${NOTIFICATION_POSTGRES_DB} OWNER ${NOTIFICATION_POSTGRES_USER};

EOSQL
